// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCosz9rPTZD_sshJBWXqUfztRkDalwP9pM',
    appId: '1:275522388912:android:ae260525086150ff798c75',
    messagingSenderId: '275522388912',
    projectId: 'ecom-9cd00',
    storageBucket: 'ecom-9cd00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqUAWoGSqkn-9-2TZRp4symwaCaJQ8Rp4',
    appId: '1:275522388912:ios:9816e5bb818cae09798c75',
    messagingSenderId: '275522388912',
    projectId: 'ecom-9cd00',
    storageBucket: 'ecom-9cd00.firebasestorage.app',
    androidClientId: '275522388912-fql7rag5ml5bo0p35035t6jt8p3rtt9e.apps.googleusercontent.com',
    iosClientId: '275522388912-sct5127dk77bugopj39tqmj24bj5ecqu.apps.googleusercontent.com',
    iosBundleId: 'com.samar.upstore',
  );

}